server:
  port: 8085

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/spot}
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: create

  graphql:
    graphiql:
      enabled: true
      path: /spotemo # 안돼
  main:
    allow-bean-definition-overriding: true

auth:
  secret: ${SECRET_KEY:}

graphql:
  spqr:
    gui:
      enabled: true
  servlet:
    exception-handlers-enabled: true
