server:
  port: 8085

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spot?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: lje0818OVO!
